apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  namespace: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 30s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager-svc.prometheus-server.svc.cluster.local:80
        scheme: http
        timeout: 10s

    rule_files:
    - "/etc/prometheus/rule/rule.yml"

    scrape_configs:
    - job_name: federate-xxxx
      honor_labels: true
      params:
        match[]:
        - '{job=~"kubernetes-.*"}'
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /federate
      scheme: http
      static_configs:
      - targets:
        - x.x.x.x:30090
        labels:
          k8scluster: xxxx-k8s
    - job_name: federate-yyyy
      honor_labels: true
      params:
        match[]:
        - '{job=~"kubernetes-.*"}'
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /federate
      scheme: http
      static_configs:
      - targets:
        - y.y.y.y:30090
        labels:
          k8scluster: yyyy-k8s
