apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus-server
  labels:
    app: grafana
    component: core
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 9090
  selector:
    app: grafana
    component: core
